### ISSUE TITLE
Session Not Found - dev-master

### ISSUE THREAD

**Issue by LeVadim** [colopl/laravel-spanner#135]
Hi!!  I wanted to check with you whether you have any suggestion on how to handle/avoid these Session Not Found errors?

I think the session pool is not being cleared somehow for some reason.

Using Laravel Octane setup.

Currently when project is not accessed for around 10 hours, Session not found errors would occur for all requests

Thank you

FYI: using latest dev-master version

**Comment by taka-oyama** [comment]
Please see https://github.com/colopl/laravel-spanner/tree/5.x#session-not-found-exception-handling

Also, I suggest you run SessionPool::maintain or downsize every 30 minutes or so using cron.

**Comment by taka-oyama** [comment]
That's odd. It should be automatically retry through https://github.com/colopl/laravel-spanner/blob/master/src/Connection.php#L578-L583 after the latest changes. 

Is this a simple SELECT? Is it bound by transaction?

Also, Spanner sessions expire after 1 hour so I'm not sure where the 10 hours came from.

**Comment by taka-oyama** [comment]
I know why now. You're not returning the connection to the connection pool after the request. You need to call disconnect after every request cycle so the session has a change to return to the session pool. 

This is similar to how the connection is disconnected after every job [in the queue:worker](https://github.com/colopl/laravel-spanner/blob/master/src/SpannerServiceProvider.php#L111-L119).

**Comment by taka-oyama** [comment]
Closing this for now. Please reopen if you have further questions.

**Comment by LeVadim** [comment]
Hi @taka-oyama ! Thank you for looking into it, much appreciate it!

I think that could be it.. i did see the latest changes and though it could help.. but no
Perhaps its 1 hour, its just when system is not used overnight the workload in kubernetes needs to be restarted due to this session not found error popping up.

Added a code to terminate sessions whenever octane terminates its worker, will see if that helps, thanks so much!
![Screenshot 2023-09-21 at 2 04 28 PM](https://github.com/colopl/laravel-spanner/assets/16689198/5b0a4f28-3735-400a-a4f9-9e8bcc07f503)

**Comment by taka-oyama** [comment]
Yeah, this is a known issue and I want to fix it but the session being used is not exposed by google. I [asked for a fix](https://github.com/googleapis/google-cloud-php/issues/6284) but they've decided not to fix it unfortunately.

**Comment by taka-oyama** [comment]
I'm still wondering why this happened. Even if the error happened, the session pool should be cleared, and the currently used session should be discarded because disconnect is called in the retry handler https://github.com/colopl/laravel-spanner/blob/f9bb1f0dfc1d485e5367ffc0f7c6aec794093538/src/Connection.php#L578.

**Comment by LeVadim** [comment]
My fix did not help and back to square 0 : /

I know @taka-oyama , i checked out that repo and see that you`re trying your best to fix it..

What is weird -- it works WITHOUT PROBLEMS on my Spanner DB client that i have deployed as a singleton

I think that handleSessionNotFoundException is NEVER called

Take a look
![Screenshot 2023-09-21 at 10 13 28 PM](https://github.com/colopl/laravel-spanner/assets/16689198/4c47d450-87d9-4f5f-944a-618925fdee72)
You are checking for: Session does not exist, however, i am getting message: "Session not found: projects/...."

Perhaps you can just do
str_contains($e->getMessage(), 'Session') ? 

Thank you @taka-oyama 

![Screenshot 2023-09-21 at 10 14 45 PM](https://github.com/colopl/laravel-spanner/assets/16689198/4ff9e376-e41c-4699-be0a-847452771b3c)

**Comment by taka-oyama** [comment]
Can you paste the entire JSON part of the error message (with your project id edited out).

**Comment by taka-oyama** [comment]
if you look [here](https://github.com/googleapis/google-cloud-php/issues/5827) the description should contain "Session does not exist."

**Comment by LeVadim** [comment]
Sure, will post it as soon as it occurs the next time

Got it, but perhaps that getPrevious is not working well and thus, tried to simplify it to ensure that works first and afterwards can complicate it.

Thank you @taka-oyama

**Comment by LeVadim** [comment]
Here is a JSON: ```Google\Cloud\Core\Exception\NotFoundException: {
    "message": "Session not found: projects\/PROJECT_ID\/instances\/DB_NAME\/databases\/staging\/sessions\/AH67Lq69fYjEqKBz44M8O1VmvK5Xh6rlVpjZU15e8mm-sTtJU5wn7zpOcL-Kmw",
    "code": 5,
    "status": "NOT_FOUND",
    "details": [
        {
            "@type": "google.rpc.resourceinfo-bin",
            "resourceType": "type.googleapis.com\/google.spanner.v1.Session",
            "resourceName": "projects\/PROJECT_ID\/instances\/DB_NAME\/databases\/staging\/sessions\/AH67Lq69fYjEqKBz44M8O1VmvK5Xh6rlVpjZU15e8mm-sTtJU5wn7zpOcL-Kmw",
            "owner": "",
            "description": "Session does not exist."
        },
        {
            "@type": "grpc-status-details-bin",
            "data": "<Unknown Binary Data>"
        }
    ]
}```

```Stack trace:
#0 src/www/html/vendor/google/cloud/Core/src/GrpcRequestWrapper.php(200): Google\Cloud\Core\GrpcRequestWrapper->convertToGoogleException(Object(Google\ApiCore\ApiException))
#1 [internal function]: Google\Cloud\Core\GrpcRequestWrapper->handleStream(Object(Google\ApiCore\ServerStream))
#2 src/www/html/vendor/google/cloud/Spanner/src/Result.php(192): Generator->valid()
#3 [internal function]: Google\Cloud\Spanner\Result->Google\Cloud\Spanner\{closure}()
#4 src/www/html/vendor/google/cloud/Core/src/ExponentialBackoff.php(97): call_user_func_array(Object(Closure), Array)
#5 src/www/html/vendor/google/cloud/Spanner/src/Result.php(190): Google\Cloud\Core\ExponentialBackoff->execute(Object(Closure))
#6 [internal function]: Google\Cloud\Spanner\Result->rows()
#7 src/www/html/vendor/colopl/laravel-spanner/src/Connection.php(260): iterator_to_array(Object(Generator))
#8 src/www/html/vendor/colopl/laravel-spanner/src/Connection.php(472): Colopl\Spanner\Connection->Colopl\Spanner\{closure}('select * from `...', Array)
#9 src/www/html/vendor/colopl/laravel-spanner/src/Connection.php(583): Colopl\Spanner\Connection->Colopl\Spanner\{closure}()
#10 src/www/html/vendor/colopl/laravel-spanner/src/Connection.php(528): Colopl\Spanner\Connection->handleSessionNotFoundException(Object(Closure))
#11 src/www/html/vendor/colopl/laravel-spanner/src/Connection.php(471): Colopl\Spanner\Connection->withSessionNotFoundHandling(Object(Closure))
#12 src/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(755): Colopl\Spanner\Connection->runQueryCallback('select * from `...', Array, Object(Closure))
#13 src/www/html/vendor/colopl/laravel-spanner/src/Connection.php(258): Illuminate\Database\Connection->run('select * from `...', Array, Object(Closure))
#14 src/www/html/vendor/colopl/laravel-spanner/src/Query/Builder.php(148): Colopl\Spanner\Connection->selectWithOptions('select * from `...', Array, Array)
#15 src/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2740): Colopl\Spanner\Query\Builder->runSelect()
#16 src/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(3294): Illuminate\Database\Query\Builder->Illuminate\Database\Query\{closure}()
#17 src/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2739): Illuminate\Database\Query\Builder->onceWithColumns(Array, Object(Closure))
#18 src/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(737): Illuminate\Database\Query\Builder->get(Array)
#19 src/www/html/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(721): Illuminate\Database\Eloquent\Builder->getModels(Array)
#20 src/www/html/vendor/laravel/framework/src/Illuminate/Database/Concerns/BuildsQueries.php(300): Illuminate\Database\Eloquent\Builder->get(Array)```

**Comment by taka-oyama** [comment]
Thank you for the logs. It seems like it did retry because it's calling `handleSessionNotFoundException`

```
#10 src/www/html/vendor/colopl/laravel-spanner/src/Connection.php(528): Colopl\Spanner\Connection->handleSessionNotFoundException(Object(Closure))
```

So it seems like the session is not belong cleared for some reason.

Are you using the default session pool defined in `SpannerServiceProvider`?

**Comment by taka-oyama** [comment]
If you see https://github.com/colopl/laravel-spanner/blob/f9bb1f0dfc1d485e5367ffc0f7c6aec794093538/src/Connection.php#L578-L581

You can see that `disconnect` puts back the current session to the session pool, and `clearSessionPool` deletes all the sessions. So in theory, there should be no dangling sessions left. So I assume that either the session is not being put back, or the session pool is not being cleared.

**Comment by LeVadim** [comment]
100%.. i do see that your code does it correctly, without doubts

But unfortunately, something is not working

Perhaps its related to Octane

**Comment by taka-oyama** [comment]
Closing due to no activity. Please re-open if you find something upon further debugging.
