### ISSUE TITLE
misleading error when incorrect name of db/project/instance is used

### ISSUE THREAD

**Issue by oprudkyi** [colopl/laravel-spanner#40]
When trying to access non-existent db there is error 
```

A session did not become available in the allotted number of attempts. {"exception":"[object] (RuntimeException(code: 0): A session did not become available in the allotted number of attempts. at /var/www/vendor/google/cloud-spanner/src/Session/CacheSessionPool.php:741)
[stacktrace]
#0 /var/www/vendor/google/cloud-core/src/Lock/LockTrait.php(67): Google\\Cloud\\Spanner\\Session\\CacheSessionPool->Google\\Cloud\\Spanner\\Session\\{closure}()
#1 /var/www/vendor/google/cloud-spanner/src/Session/CacheSessionPool.php(745): Google\\Cloud\\Core\\Lock\\SemaphoreLock->synchronize(Object(Closure))
#2 /var/www/vendor/google/cloud-spanner/src/Session/CacheSessionPool.php(296): Google\\Cloud\\Spanner\\Session\\CacheSessionPool->waitForNextAvailableSession()
#3 /var/www/vendor/google/cloud-spanner/src/Database.php(2022): Google\\Cloud\\Spanner\\Session\\CacheSessionPool->acquire('rw')
#4 /var/www/vendor/google/cloud-spanner/src/Database.php(849): Google\\Cloud\\Spanner\\Database->selectSession('rw', Array)
#5 /var/www/vendor/colopl/laravel-spanner/src/Colopl/Spanner/Concerns/ManagesTransactions.php(88): Google\\Cloud\\Spanner\\Database->runTransaction(Object(Closure), Array)
#6 /var/www/vendor/colopl/laravel-spanner/src/Colopl/Spanner/Connection.php(510): Colopl\\Spanner\\Connection->Colopl\\Spanner\\Concerns\\{closure}()
#7 /var/www/vendor/colopl/laravel-spanner/src/Colopl/Spanner/Concerns/ManagesTransactions.php(93): Colopl\\Spanner\\Connection->withSessionNotFoundHandling(Object(Closure))

```

probably existence of project/instance/db should be checked somehow or at least error message should include project/instance/db to simplify debugging

**Comment by taka-oyama** [comment]
Thank you for the issue. Yes, I agree. 
Perhaps this is something the underlying Google API should address.

**Comment by taka-oyama** [comment]
I occasionally have a chance to talk to the backend people working on Cloud Spanner.

I will see if I can convince them to implement a better error in the backend.
